apiVersion: v1
kind: Pod
metadata:
  name: kube-podmaster-kubeturbo
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kubeturbo-podmaster
    image: gcr.io/google_containers/podmaster:1.1
    command:
    - /podmaster
    - --etcd-servers=<ETCD-SERVER-ADDRESS>
    - --key=controller
    - --whoami=<MASTER-ID>
    - --source-file=/src/manifests/kubeturbo.yaml
    - --dest-file=/dst/manifests/kubeturbo.yaml
    volumeMounts:
    - mountPath: /src/manifests
      name: manifest-src
      readOnly: true
    - mountPath: /dst/manifests
      name: manifest-dst
  volumes:
  - hostPath:
      path: /srv/kubernetes/manifests
    name: manifest-src
  - hostPath:
      path: /etc/kubernetes/manifests
    name: manifest-dst
