apiVersion: v1
kind: Pod
metadata:
  name: kubeturbo
  namespace: kube-system
  labels:
    name: kubeturbo
spec:
  hostNetwork: true
  containers:
  - name: kubeturbo
    image: vmturbo/kubeturbo:1.0
    command:
      - /bin/kubeturbo
    args:
      - --v=2
      - --master=<Kubernetes_API_Server_Address>
      - --etcd-servers=<ETCD_Endpoint>
      - --config-path=/etc/kubeturbo/config
    volumeMounts:
    - name: vmt-config
      mountPath: /etc/kubeturbo
      readOnly: true
  volumes:
  - name: vmt-config
    hostPath:
      path: /etc/kubeturbo
  restartPolicy: Always
