apiVersion: v1
kind: Pod
metadata:
  name: kubeturbo
  labels:
    name: kubeturbo
spec:
#  uncomment the following line if master is http://127.0.0.1:8080
#  hostNetwork: true
  containers:
  - name: kubeturbo
#   change version
    image: vmturbo/kubeturbo:v5.9.0
    command:
      - /bin/kubeturbo
    args:
      - --v=2
#     change master url
      - --master=http://1.2.3.4:8080
      - --turboconfig=/etc/kubeturbo/config
    volumeMounts:
    - name: turbo-config
      mountPath: /etc/kubeturbo
      readOnly: true
  volumes:
  - name: turbo-config
    hostPath:
#     change the path to config
      path: /etc/kubeturbo
  restartPolicy: Always
